package pe.cinema.util;
public class AppConstants {

    public static final String PELICULA_NO_ENCONTRADA = "PELÍCULA NO ENCONTRADA";
    public static final String PELICULA_PORTADA_OBLIGATORIA = "LA PORTADA DE LA PELÍCULA ES OBLIGATORIA";
    public static final String PELICULA_FECHA_BUSQUEDA = "DEBE PROPORCIONAR UNA FECHA DE ESTRENO PARA BUSCAR";
    public static final String PELICULA_GENERO_BUSQUEDA = "DEBE PROPORCIONAR AL MENOS UN GÉNERO PARA BUSCAR";

    public static final String GENERO_NO_ENCONTRADO = "GÉNERO NO ENCONTRADO";
    public static final String GENERO_NO_ENCONTRADO_TITULO = "GÉNERO NO ENCONTRADO CON ESE TÍTULO";
    public static final String GENERO_EXISTE = "EL GÉNERO YA EXISTE";

    public static final String PELICULA_TITULO_EXISTE = "YA EXISTE UNA PELÍCULA CON ESTE TÍTULO";
    public static final String ARCHIVO_VACIO = "NO SE PUEDE ALMACENAR UN ARCHIVO VACÍO O NULO";
    public static final String NOMBRE_ARCHIVO_INVALIDO = "NOMBRE DE ARCHIVO INVÁLIDO";
    public static final String ERROR_ALMACENAR_ARCHIVO = "ERROR AL ALMACENAR EL ARCHIVO";
    public static final String ERROR_ELIMINAR_ARCHIVO = "ERROR AL ELIMINAR EL ARCHIVO";
    public static final String NOMBRE_ARCHIVO_OBLIGATORIO = "EL NOMBRE DEL ARCHIVO NO PUEDE SER VACÍO";
    public static final String ARCHIVO_NO_ENCONTRADO = "NO SE PUDO ENCONTRAR EL ARCHIVO";
    public static final String ERROR_INICIALIZAR_ALMACEN = "ERROR AL INICIALIZAR EL ALMACENAMIENTO DE ARCHIVOS";

}